### ISSUE TITLE
Upgrade to winston 3.0 

### ISSUE THREAD

**Issue by avanderpluijm** [ortexx/winston-transport-sequelize#6]
Hi, any plans on upgrading to winston 3? 

sequelize is a legacy winston transport. Consider upgrading: 
Upgrade docs: https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md

**Comment by ortexx** [comment]
I've upgraded. You can check.

**Comment by avanderpluijm** [comment]
Thanks! but I think you forgot to update index.js? (I see test is updated)

**Comment by ortexx** [comment]
it seems, there is no need for changes. Write here if you face an error.

**Comment by avanderpluijm** [comment]
ok, the notice is: 
`sequelize is a legacy winston transport. 
Consider upgrading: - Upgrade docs: https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md`

Reading in the upgrade doc: https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md 
`When writing transports use winston-transport instead of winston.Transport.`

**Comment by ortexx** [comment]
done

**Comment by avanderpluijm** [comment]
nice, thanks!
