### ISSUE TITLE
Message size limited to 255

### ISSUE THREAD

**Issue by PhilHannent** [ortexx/winston-transport-sequelize#7]
Using Winston and `mssql` dialect, the table column `message` ends up being `NVARCHAR(255)`:

https://github.com/ortexx/winston-transport-sequelize/blob/master/index.js#L25

This leads to Sequalize messages of:
`Unhandled rejection SequelizeDatabaseError: String or binary data would be truncated.`

It would be better if message was `TEXT`.

**Comment by ortexx** [comment]
Done, thanks!
